# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v3
          
        - name: 'Setup Go env'
          uses: actions/setup-go@v3
          with:
            go-version: '1.17.0'
      
        - name: 'Build Go file'
          run: go build -v ./...
        
  CD:
    runs-on: ubuntu-latest
    steps:
        - name: 'Build and Publish Docker Image'
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }} 
            
        - name: "Build and Push"
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: midhatdrops/golang-actions:${{ github.sha }}
